<?php
return [
    'Training' => 'Ausbildung',
    'Employee Training Overview' => 'Mitarbeiterschulung Übersicht',
    'Assign training to all employees with title:' => 'Schulung allen Mitarbeitern mit Titel zuweisen:',
    'With storage location in:' => 'Mit Lagerort in:',
    'Select all' => 'Alle auswählen',
    'Select Title' => 'Titel auswählen',
    'Assign now' => 'Jetzt zuweisen',
    'Assign training to specific users' => 'Zuweisung von Schulungskursen an bestimmte Benutzer',
    'Or select time when the training should be assigned:' => 'Oder wählen Sie den Zeitpunkt aus, zu dem das Training zugewiesen werden soll:',
    'Edit questions' => 'Fragen bearbeiten',
    'Search employees...' => 'Mitarbeiter finden...',
    'Full name' => 'Vollständiger Name',
    'Job' => 'Job',
    'Roles' => 'Rollen',
    'Location' => 'Standort',
    'Last login' => 'Letzter Login',
    'Training assigned time' => 'Zugewiesene Ausbildungszeit',
    'Training complete time' => 'Zeitpunkt des Abschlusses der Ausbildung',
    'Assigned training' => 'Zugewiesene Ausbildung',
    'Answers from the latest training' => 'Antworten aus der letzten Ausbildung',
    'Question:' => 'Frage:',
    'Answer:' => 'Antwort:',
    'Edit Training Questions' => 'Schulungsfragen bearbeiten',
    'Back to overview' => 'Zurück zur Übersicht',
    'Select title' => 'Titel auswählen',
    '+ Add question' => '+ Frage hinzufügen',
    '- Remove question' => '- Frage entfernen',
    'Advanced settings ' => 'Erweiterte Einstellungen ',
    'Assign question(s) to all titles' => 'Frage allen Titel(n) zuordnen',
    'Training Assignment' => 'Ausbildungsauftrag',
    'Submit' => 'Einreichen',
    'No. of completed trainings' => 'Anzahl der abgeschlossenen Fortbildungskurse',
];
